version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENVIRONMENT=dev
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    depends_on:
      - dex
    networks:
      - app-network

  dex:
    image: ghcr.io/dexidp/dex:v2.37.0
    command: ["dex", "serve", "/etc/dex/dex-config.yaml"]
    ports:
      - "5556:5556"
    volumes:
      - ./deploy/dex/dex-config.yaml:/etc/dex/dex-config.yaml
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
