app:
  name: "gin-microservice-boilerplate"
  environment: "dev"

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 10  # seconds
  write_timeout: 10 # seconds

logger:
  level: "info"  # debug, info, warn, error

database:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: microservice
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # seconds

auth:
  jwt_secret: "supersecretkey"
  jwt_expiry_hours: 1
  superadmin_email: "admin@example.com"

rbac:
  model_path: "/app/internal/infrastructure/rbac/model.conf"
  policy_path: "/app/internal/infrastructure/rbac/policy.csv"
