app:
  name: "gin-microservice-boilerplate"
  environment: "dev"

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 10  # seconds
  write_timeout: 10 # seconds

logger:
  level: "info"  # debug, info, warn, error

database:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: microservice
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # seconds

auth:
  dex_url: "http://localhost:5556/dex"
  client_id: "frontend"
  client_secret: "frontend-secret"
  redirect_uri: "http://localhost:8080/auth/callback"
  # GitHub OAuth credentials should be set in environment-specific config files
  github_client_id: ""
  github_client_secret: ""
  superadmin_email: "admin@example.com"
